### ISSUE TITLE
v1.4.1 not available in JOSM plugin downloader?

### ISSUE THREAD

**Issue by ZLima12** [JOSM/josm-gridify#11]
I'm using JOSM 16731, and I had been experiencing the bug that was fixed in commit b254379. I assumed the issue had to do with the updated version of JOSM (which is true), so I periodically tried to update my plugins. Eventually, after not receiving any updates, I came here and saw that the issue had already been fixed. I downloaded v1.4.1 and v1.4.0, compared checksums with the jar file JOSM was using, and sure enough, JOSM was still using v1.4.0. I replaced JOSM's copy with v1.4.1 and everything started working again. Has v1.4.1 been made available from the plugin downloader in JOSM?

**Comment by jdhoek** [comment]
It is [available](https://josm.openstreetmap.de/wiki/Plugins), as far as I can tell, but I had to explicitly click on `Download the list of available plug-ins` before it got the newest version. Perhaps your local cache of available plugins was out of date? I would expect the `Update the selected plug-ins` button to do that automatically, but perhaps not.
