### ISSUE TITLE
Feature request: improve row/column editing interaction for keyboard use

### ISSUE THREAD

**Issue by mirror176** [JOSM/josm-gridify#6]
Each time I open the dialog I press tab and shift tab to go back and forth between the column and row values. It would be helpful to have grid size be the first thing asked as it is likely to be changed from object to object. When navigating between row/column values it would help to have the value highlighted for quickly overwriting with the new value. Why does pressing enter first refresh the grid and require a second press to accept? Are there examples where it is preferred to keep the source way when using this tool? Does it ever involve the tags being copied when the original was left behind?
A current attempt to change the default 2x3 to 1x6 requires 8 keys of: [tab] 1 [del] [tab] 6 [del] [enter] [enter]
A simplified approach could be 4 keys of: 1 [tab] 6 [enter]
Three is an extra [tab] [tab] [space] if not keeping the original area is desired at present.
Thanks for the great plugin.

**Comment by jdhoek** [comment]
Release `v1.3` should fix this issue.
