### ISSUE TITLE
Defect: Hangs JOSM Latest on Catalina

### ISSUE THREAD

**Issue by codesman** [JOSM/josm-gridify#9]
First, thanks for contributing this plugin.  Awesome, have been waiting for this a long time.  Many uses outside of parking lots! Unfortunately, I haven't been able to feel the love...

I'm taking the fact that you have left the issues feature open on this repo, that you are taking bug reports here. Here's mine!

**What you expected to happen?**
That the gridify plugin would convert a 4 node area to a grid of ways

**What actually happened?**
Nothing. Dialog does not appear. JOSM hangs and requires force quit.

**Steps to reproduce:**
- Open JOSM 16386 in macOS Catalina
- Create a new layer
- Draw a closed way with 4 nodes and select it
- Select Gridify from the More Tools menu
- Notice that a dialog does not open and you get a beachball instead

**Comment by codesman** [comment]
Forgot to add that the use case I was trying it on was to create a row of honey buckets!  lol

**Comment by jdhoek** [comment]
Did you check with the latest version of the plugin? A crash on MacOS was fixed in #8.

The plugin version in JOSM should be `1588746833`.

**Comment by codesman** [comment]
🤦 Nope, didn't do that!  Thanks, and sorry for the false alarm.

**Comment by jdhoek** [comment]
No problem, glad it works.
